Vagrant.configure("2") do |config|
  config.vm.box = "fvmoraes/eklnj/bionic64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provider "virtualbox" do |vb|
  vb.memory = "3072"
  end
end
