Vagrant.configure("2") do |config|
  config.vm.box = "fvmoraes/zgam/bionic64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 3000, host: 3080
  config.vm.network "public_network", type: "dhcp", bridge: "wlp6s0"
  config.vm.usable_port_range = 10050..10051
  config.vm.provider "virtualbox" do |vb|
  vb.memory = "2048"
  vb.cpus = 2
  end
end
